### ISSUE TITLE
Add a fallback for user profile image if avatarUrl is null

### ISSUE THREAD

**Issue by thedroiddiv** [Chesire/Nekome#1085]
The default fallback image for user profile doesn't looks good. It would be good to have a more generic or some random profile picture in case avatarUrl for user is null.

<img src="https://github.com/Chesire/Nekome/assets/69595691/17f05b83-e6c3-4752-b104-9a736cfd6060" width="300px" />

**Comment by Chesire** [comment]
Good point, the error image is pretty ugly. I'll add a default avatar icon which will at least look a bit nicer
