### ISSUE TITLE
Add Monochrome icon for android 12 and above.

### ISSUE THREAD

**Issue by itnerd7** [Chesire/Nekome#1146]
More and more apps are starting to include a monochrome icon along with their normal icon to support the 'themed icon' setting introduced in android 12. 

Since Nekome's icon is already kinda monochrome, thus it shouldn't be that hard right ?!
 I can't program in kotlin or ruby, but if necessary i'll be willing to atleast make a monochrome icon for nekome.
 Waiting to hear from @Chesire :)

**Comment by Chesire** [comment]
Good idea, I'll take a look at this when i get a chance. Feel free to add a PR if you want to add it before i manage to take a look though

**Comment by ITnerd1** [comment]
Sure ! I'll try to make a monochrome icon when I get the time. Meanwhile, do look into it when you get the chance :)

**Comment by Chesire** [comment]
Made a change to add a basic monochrome icon will push it out in the next release, its not the prettiest but its better than none. 
I'll leave this ticket open incase somebody makes a nicer one

**Comment by ITnerd1** [comment]
Absolutely !! I'm not an expert at making icons, hopefully someone will make a good one. For now the one you made should be good !

**Comment by itnerd7** [comment]
I made a new icon ! I opened a new ticket for it.
