### ISSUE TITLE
Full screen login flow

### ISSUE THREAD

**Issue by Chesire** [Chesire/Nekome#120]
The login flow currently has a white background, with the bar visible at the top of the screen. It would probably look better if the bar was made white to match the background, with black icons so they are still visible.

These would be visible only on the login module screens, then disappear once back on the main application screens.

**Comment by devrahul-2508** [comment]
Do You want to change the colour of the top status bar? If that is then I would like to work on this issue...

**Comment by Chesire** [comment]
The plan was to make the top status bar the same colour as the background in the login screens only. I haven't thought too much about it recently though... I would be happy for you to pickup this issue 😄
