### ISSUE TITLE
F-Droid support

### ISSUE THREAD

**Issue by austinhuang0131** [Chesire/Nekome#596]
Have the developers considered getting this app included on [F-Droid](https://f-droid.org)?

Given that Fastlane is already used here, all that's left is to submit metadata and wait for approval.

**Comment by Chesire** [comment]
I had thought about it, but had not got around to it.
I've opened an issue with them to try to get it included https://gitlab.com/fdroid/rfp/-/issues/1786, thanks for the nudge!
I'll close this down once I confirm it has been added.
