### ISSUE TITLE
Can skip login details screen

### ISSUE THREAD

**Issue by Chesire** [Chesire/Nekome#722]
If activity recreation occurs while sitting on the login details screen, then the user will be taken to the anime/manga list without being logged in.
The reason for this is likely that when the activity is recreated
```kotlin
        if (savedInstanceState == null && !viewModel.userLoggedIn) {
```
is used in the `onCreate` which on recreation is skipped because `savedInstanceState `is not null so the nav graph goes straight to the anime/manga list.
Should be a case of making sure it doesn't default to anime/manga and instead doing it manually.

**Comment by shalva97** [comment]
This can be closed 🔥
