### ISSUE TITLE
Add title preference setting

### ISSUE THREAD

**Issue by Soundtoxin** [Chesire/Nekome#735]
For some reason I see "Attack on Titan" in my list. I usually have romaji titles displayed and would strongly prefer that here. It's a bit disorienting not having them, because I sort by title, and so things actually aren't where I expect this way. (A section vs S section in this case)

**Comment by Chesire** [comment]
The title that is used in the app is what Kitsu refers to as the "canonical title". It should be possible to pull down the `titles` object that they provide in their API and add a preference setting to choose which one to use in the app
