### ISSUE TITLE
Can't refresh if one of the lists is empty

### ISSUE THREAD

**Issue by CyNide4869** [Chesire/Nekome#746]
I only have manga added to my library, on the first login it was able to successfully sync the data, but after I tried updating an entry on the website and refreshed the list on the app, it failed to sync the contents.

I was able to successfully refresh the list if at least one anime entry was in my library, otherwise the sync fails.
So I'm assuming that the code assumes both the lists must have some entries.
Hope it gets fixed, Thanks for the app.

![screenshot](https://i.imgur.com/4ZGsU69.jpg)

**Comment by Chesire** [comment]
Thanks for this issue, I should have a fix for this out soon 👍
