### ISSUE TITLE
[Feature Request] Material You Support

### ISSUE THREAD

**Issue by oomfiee** [Chesire/Nekome#925]
Please consider updating the interface to material you, 
Material You allow for better UI consistency across devices, it makes them easier to use, and it adapts to user color scheme preferences.

**Comment by Chesire** [comment]
I would love to get this integrated, the app is currently being rewritten to use Compose, so once that is done hopefully it will be simple to add this functionality.

**Comment by Chesire** [comment]
This will be available in the next release
