### ISSUE TITLE
Settings option for default starting screen

### ISSUE THREAD

**Issue by Chesire** [Chesire/Nekome#93]
Add an option into settings that allows the user to choose their default starting screen. Currently it defaults to "Anime", but some users may only use the app to track their manga usage so it would be nice to allow them to default to Manga.

**Comment by subbramanil** [comment]
@Chesire Are you considering opening up any issues for Hactoberfest? I found the app through Github recommendations, although it's not tagged with Hacktoberfest. I would love to work on this issue, be it Hacktoberfest or not. But it would help if the repo is open for Hacktoberfest contributions.

**Comment by Chesire** [comment]
Sure thing, I have added the hacktoberfest topic now!
