### ISSUE TITLE
Can't Login.

### ISSUE THREAD

**Issue by liberec0** [Chesire/Nekome#992]
Affected Version 2.0.1.
Partially affected versions: <2.0.1

In the latest version, login is functionality is broken, so upon entering the email and password, a generic error shows up: error trying to login, please try again (can confirm that logging in is still possible from previous versions.)

Moreover, Cannot refresh lists, add, search, delete any entries, even in previous versions, same generic error: error trying to refresh lists, please try again.
Seems to me that kitsu changed something in their API or something :/

**Comment by liberec0** [comment]
Got it ! Hopefully someone can figure this out in the meantime :)

**Comment by Chesire** [comment]
This should now be fixed by version 2.0.2 which will be rolled out shortly
